services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: natjus_elastic
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - natjus_net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: natjus_kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - natjus_net

  minio:
    image: minio/minio:latest
    container_name: natjus_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minio@natjus
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data
    networks:
      - natjus_net

  indexer:
    build: .
    container_name: natjus_indexer
    volumes:
      - .:/app
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTIC_USERNAME: elastic
      ELASTIC_PASSWORD: changeme
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET_NAME: natjus-notas
      MINIO_SECURE: "false"
    depends_on:
      - elasticsearch
      - minio
    networks:
      - natjus_net

volumes:
  es_data:

networks:
  natjus_net:
    driver: bridge